[platformio]
default_envs = uno_bench

[env]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -Wall
    -Wextra
    -Wpedantic

[env:uno_bench]
build_flags =
    ${env.build_flags}
    -DTECHNIC_RC_ENABLE_MONITOR_COMMANDS=1

[env:uno_bts7960]
build_flags =
    ${env.build_flags}
    -DTECHNIC_RC_ENABLE_BTS7960=1
    -DTECHNIC_RC_ENABLE_CURRENT_PROTECTION=1
    -DTECHNIC_RC_ENABLE_DYNAMIC_BRAKING=0
    -DTECHNIC_RC_ENABLE_MONITOR_COMMANDS=0
