[platformio]
default_envs = esp32_diagnostics
src_dir = main

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21/platform-espressif32.zip
framework = espidf
board = esp32dev
monitor_speed = 115200
monitor_filters = direct
build_flags =
    -std=gnu++17
    -Wall
    -Wextra
    -Wpedantic
    -DTECHNIC_RC_ENABLE_SERIAL_DIAGNOSTICS=1

[env:esp32_diagnostics]
build_flags =
    ${env.build_flags}
    -DTECHNIC_RC_ENABLE_BTS7960=0
    -DTECHNIC_RC_ENABLE_SERVO=0

[env:esp32_bts7960]
build_flags =
    ${env.build_flags}
    -DTECHNIC_RC_ENABLE_BTS7960=1
    -DTECHNIC_RC_ENABLE_SERVO=1
